---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: catalin-eks
  region: eu-central-1
  tags:
    project: terraform-aws-infrastructure

nodeGroups:
  - name: worker-node
    instanceType: c7i-flex.large
    desiredCapacity: 3
